language: node_js
cache:
  directories:
  - node_modules
install:
- bundle install
- npm install
script:
- bundle exec jekyll build
branches:
  except:
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
env:
  global:
    secure: Ji3szRlXsjzGUpmryV6ecZEcpqXAx9zbL1Icp4O5hIxiQb+rGetAYG+lYgnVT4560wuwr3p0yVyJm1JfdUWz05rL8+kKu3kdGjHf8f79OTWIPI8NxsNBecaiMAS+3oE3v78F5NpDUcekFl1QS+uEvbLb68q7dfDdO4U1//zTQ04=
