language: node_js
node_js:
  - '0.10'
env:
  global:
    secure: TCho+s61OgenfIuQFoTZLBrl/IfVEv8JUX5XhsGn71strwsDCdy4Y5hrsyfogFrXEemDd60z/igCL9yUSIjatWgmGtEUziVxy24awEwokKE1LOh01Qi3RxCxXDpLY8T2eR1xGEDFrUq0dIWzmtx/LHDPr7i/rUmXnc7aVU3atLQ=
install: npm install
before_script: npm run build
after_success: ./deploy.sh
